from sqlalchemy.orm import Session
from app.models.gis_models import Habitation, RiskAssessment, VulnerabilityAssessment, RedZoneAssessment, RelocationAllocation

def generate_habitation_narrative(db: Session, habitation_id: int) -> dict:
    """
    Generates a generative narrative report summarizing the deterministic findings.
    This simulates an LLM call to a generative model.
    """
    hab = db.query(Habitation).filter(Habitation.id == habitation_id).first()
    if not hab:
        raise ValueError("Habitation not found")
        
    risk = db.query(RiskAssessment).filter(RiskAssessment.habitation_id == habitation_id).first()
    vuln = db.query(VulnerabilityAssessment).filter(VulnerabilityAssessment.habitation_id == habitation_id).first()
    red = db.query(RedZoneAssessment).filter(RedZoneAssessment.habitation_id == habitation_id).first()
    alloc = db.query(RelocationAllocation).filter(RelocationAllocation.habitation_id == habitation_id).first()
    
    # ---------------------------------------------------------
    # Simulated LLM generation based on deterministic inputs
    # ---------------------------------------------------------
    narrative_lines = []
    narrative_lines.append(f"Habitation {hab.name} is currently flagged as a {red.classification if red else 'GREEN'} zone.")
    
    if risk:
        narrative_lines.append(f"It faces a {risk.risk_level} risk profile (Score: {risk.score}) due to environmental hazard intersections.")
    
    if vuln:
        narrative_lines.append(f"Social vulnerability is computed at {vuln.score}/100.")
        
    if alloc:
        if alloc.allocation_status == "FEASIBLE":
            narrative_lines.append(f"A relocation strategy is fully FEASIBLE, with capacity secured at Candidate Site {alloc.site_id}.")
        elif alloc.allocation_status == "PARTIAL":
            narrative_lines.append(f"Relocation is only PARTIALLY FEASIBLE due to capacity constraints at the nearest sites.")
        else:
            narrative_lines.append(f"No feasible relocation strategy exists. Immediate multi-site expansion is required.")
            
    if hab.population and hab.population > 5000:
        narrative_lines.append("Warning: The sheer size of this population cluster severely complicates rapid evacuation.")
        
    narrative_text = " ".join(narrative_lines)
    
    return {
        "habitation_id": habitation_id,
        "narrative": narrative_text,
        "generation_status": "SUCCESS",
        "methodology": "AI-ASSISTED",
        "underlying_data": "DETERMINISTIC",
        "disclaimer": "This narrative was generated by an AI assistant summarizing strictly deterministic backend evaluations. Do not rely on AI for raw metric generation."
    }
